package com.example.hp.college.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hp.college.bean.TzggContact;

import com.example.hp.college.bean.dao.TzggContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tzggContactDaoConfig;

    private final TzggContactDao tzggContactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tzggContactDaoConfig = daoConfigMap.get(TzggContactDao.class).clone();
        tzggContactDaoConfig.initIdentityScope(type);

        tzggContactDao = new TzggContactDao(tzggContactDaoConfig, this);

        registerDao(TzggContact.class, tzggContactDao);
    }
    
    public void clear() {
        tzggContactDaoConfig.clearIdentityScope();
    }

    public TzggContactDao getTzggContactDao() {
        return tzggContactDao;
    }

}
