package com.example.hp.college.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hp.college.bean.CfbgContact;
import com.example.hp.college.bean.TzggContact;

import com.example.hp.college.bean.dao.CfbgContactDao;
import com.example.hp.college.bean.dao.TzggContactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cfbgContactDaoConfig;
    private final DaoConfig tzggContactDaoConfig;

    private final CfbgContactDao cfbgContactDao;
    private final TzggContactDao tzggContactDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cfbgContactDaoConfig = daoConfigMap.get(CfbgContactDao.class).clone();
        cfbgContactDaoConfig.initIdentityScope(type);

        tzggContactDaoConfig = daoConfigMap.get(TzggContactDao.class).clone();
        tzggContactDaoConfig.initIdentityScope(type);

        cfbgContactDao = new CfbgContactDao(cfbgContactDaoConfig, this);
        tzggContactDao = new TzggContactDao(tzggContactDaoConfig, this);

        registerDao(CfbgContact.class, cfbgContactDao);
        registerDao(TzggContact.class, tzggContactDao);
    }
    
    public void clear() {
        cfbgContactDaoConfig.clearIdentityScope();
        tzggContactDaoConfig.clearIdentityScope();
    }

    public CfbgContactDao getCfbgContactDao() {
        return cfbgContactDao;
    }

    public TzggContactDao getTzggContactDao() {
        return tzggContactDao;
    }

}
